Add dictionary definition for '3-click Rule'
cherryontech/website pull request #158
Opened 2022-10-01 03:27 UTC by Sriparno08

## This PR fixes...

the lack of dictionary definition for '3-click Rule'

## What I did...

- Add dictionary definition for '3-click Rule'

## How to test...

1. Navigate to /dictionary
1. Search '3-click Rule'
1. See the definition

2022-10-03 23:24 UTC, novellac requested changes

2022-10-03 23:24 UTC, novellac commented on src/assets/content/dictionary/3-click-rule.md
> +- sourceurl: https://en.wikipedia.org/wiki/Three-click_rule
```suggestion
definition: 3-click Rule suggests that a user of a website should be able to find any information within three mouse clicks. Else, they will likely become frustrated and leave the site.
sources:
- sourceurl: https://en.wikipedia.org/wiki/Three-click_rule
```
nitpick: Almost there! I've suggested to remove the extra quotation marks, and add the term into the definition. You can click accept to accept the suggestion, or you can make another commit to update the definition. Afterwards I'll be happy to accept and merge!

2022-10-04 19:02 UTC, Sriparno08 commented
I have committed the suggested changes, @novellac. Please take a look!

2022-10-11 00:42 UTC, novellac approved these changes
Thanks for contributing! Happy Hacktoberfest 🍁

2022-10-11 00:43 UTC, merged