Add dictionary definition for 'Aesthetic'
cherryontech/website pull request #165
Opened 2022-10-03 06:51 UTC by shagunZ

## This PR fixes...
The lack of dictionary definition and perspective for 'Aesthetic'

## What I did...

-Add dictionary definition for aesthetic
-Add dictionary perspective for aesthetic

## How to test...

_In a list format, tell us how to test this PR._
Ex:

1. Navigate to /dictionary
1. Search "Aesthetic"
1. See definition and perspective show up under term "aesthetic"
2. check grammar and types

## I learned...

As a beginner I learned how to contribute to open source repository.

2022-10-03 07:45 UTC, shagunZ commented
can someone please tell me what got wrong ? why it is'nt acceptable?

2022-10-04 00:09 UTC, novellac requested changes
Almost there! I think the suggestion I made will unbreak the build. I'll be happy to approve and merge when we get the build working.

2022-10-04 00:09 UTC, novellac commented on src/assets/content/dictionary/aesthetic.md
> +definition:"Aesthic is a particular conception of beauty or art, a particular taste for or approach to what is pleasing to the senses and especially sight"
```suggestion
definition: Aesthic is a particular conception of beauty or art, a particular taste for or approach to what is pleasing to the senses and especially sight.
```
Bug: I think the lack of a space between `definition:` and `Aesthetic` is breaking the build. You can accept this suggestion via the Github UI, or you can make an additional commit to this PR, as you like.

2022-10-05 02:29 UTC, novellac commented
Closing, as I've just merged in your previous PR for the same term, #179

2022-10-05 02:29 UTC, closed without merging