Add dictionary definition for 'bug'
cherryontech/website pull request #166
Opened 2022-10-03 07:59 UTC by shagunZ

## This PR fixes...

The lack of dictionary definition and perspective for 'bug'

## What I did...

-Add dictionary definition for bug.
-Add dictionary perspective for bug.

## How to test...

_In a list format, tell us how to test this PR._
Ex:

1.Navigate to /dictionary
2.Search "Aesthetic"
3.See definition and perspective show up under term "aesthetic"
4.check grammar and types

## I learned...

As a beginner I learned how to contribute to open source repository.

2022-10-03 08:15 UTC, shagunZ commented
kindly merge my pr adding hactoberfest label on it

2022-10-04 00:14 UTC, novellac requested changes
I've suggested some changes to help the strings concat nicely. In addition, you may have to pull the most recent changes into your PR and fix a few merge conflicts.

2022-10-04 00:14 UTC, novellac commented on src/assets/content/dictionary/bug.md
> +- meaning: bug can be an error, mistake, defect or fault, which may cause failure or deviation from expected results.
```suggestion
- meaning: an error, mistake, defect or fault, which may cause failure or deviation from expected results.
```
Suggestion: The strings will compile in the style of "As a <role>, <term> means <meaning>." so I've suggested to make the meaning just a fragment. You're welcome to accept the suggestion here in the Github UI, or to make an extra commit to the PR.

2022-10-05 02:26 UTC, novellac commented
Closing, as I've just merged in your previous for the same term, PR #178 .

2022-10-05 02:26 UTC, closed without merging