Add dictionary definition for "Flowchart"
cherryontech/website pull request #168
Opened 2022-10-03 09:45 UTC by nik132-eng

## This PR fixes...

This PR fixes the Dictionary definition of "Flowcahrt"

## What I did...

- Add dictionary definition for "Flowchart".
- Add productmanager's perspective.

## How to test...

_In a list format, tell us how to test this PR._
Ex:

1. Navigate to /Dictionary
2. Search "Flowchart" 
3. See the definition and perspective show up under "Flowchart"
4. Check grammar and typos

## I learned...

learnt perfect definition

2022-10-04 00:20 UTC, novellac requested changes
Almost there! I've left one suggestion, and I'll be happy to approve and merge after that.

2022-10-04 00:20 UTC, novellac commented on src/assets/content/dictionary/flowchart.md
> +- meaning: which step/functionality work after which step. this roadmap is flowchart.
```suggestion
- meaning: which step/functionality comes after which step. A roadmap is a flowchart
```
suggestion: I've made suggestion for clarity and syntax for the perspective. You can use the Github UI to accept the suggestion here, or make an extra commit to this PR.

2022-10-04 15:54 UTC, nik132-eng commented
yes can you check this now?

2022-10-05 02:12 UTC, novellac approved these changes
Looks great! Thanks for the Hacktoberfest contribution 🍁

2022-10-05 02:12 UTC, merged