Add dictionary definition for "Ubantu"
cherryontech/website pull request #186
Opened 2022-10-04 17:04 UTC by nik132-eng

## This PR fixes...

This PR fixes the Dictionary definition of  "Ubantu"

## What I did...

- Add dictionary definition for "Ubantu".
- Add brain's perspective.

## How to test...

_In a list format, tell us how to test this PR._
Ex:

1. Navigate to /Dictionary
2. Search "Ubantu" 
3. See the definition and perspective show up under "Ubantu"
4. Check grammar and typos

## I learned...

learnt perfect definition

2022-10-11 01:54 UTC, alliequintano requested changes
Hi @nik132-eng, thank you for contributing to our tech dictionary! I like your idea for the perspective from the role of the operating system; however, we are looking for roles more like roles on a software team - like developer, designer, QA, product manager, etc. 

Are you working as or interested in one particular role? I suggest you use that are your role and write a new meaning from that perspective. Thank you!

2022-10-11 01:55 UTC, alliequintano requested changes
You can accept my suggestion to correct this small spelling mistake.

2022-10-11 01:55 UTC, alliequintano commented on src/assets/content/dictionary/ubuntu.md
> +title: Ubantu
```suggestion
title: Ubuntu
```

2022-10-11 21:52 UTC, nik132-eng commented
can you mention some issues @alliequintano ?

2022-10-12 00:58 UTC, alliequintano commented
Hi @nik132-eng, please see my previous comment about updating your 'perspective'
>Hi @nik132-eng, thank you for contributing to our tech dictionary! I like your idea for the perspective from the role of the operating system; however, we are looking for roles more like roles on a software team - like developer, designer, QA, product manager, etc.
>Are you working as or interested in one particular role? I suggest you use that are your role and write a new meaning from that perspective. Thank you!

The example in the [CONTRIBUTING.md](https://github.com/cherryontech/website/blob/pit/CONTRIBUTING.md) has a helpful example of the formatting that's needed and how to think about it. I also suggest following the directions listed there for testing locally or via the Netlify deploy preview in order to read your sentence:
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/3057984/195224860-cb9b2b78-f94b-4007-8c82-b0c654f19c1e.png">
This helps you catch mistakes like the additional period and capitalization, as well as reading the full sentence for clarity.

2023-09-07 16:28 UTC, closed without merging