Create nginx.md
cherryontech/website pull request #189
Opened 2022-10-05 03:20 UTC by ankytastic

## This PR fixes...

_This PR adds the Dictionary definition of "nginx"_

## What I did...

_Add dictionary definition of "nginx"._

## How to test...

_In a list format, tell us how to test this PR._
Ex:

1. Navigate to /Dictionary
2.Search "nginx"
3.See the definition and perspective show up under "nginx"
4.Check grammar and typos

## I learned...

_Learnt it is called as "engine-x"_

2022-10-05 03:23 UTC, ankytastic commented
[@cherryOnTechAdmin ](https://github.com/cherryontech) please accept my pr and label it for hacktoberfest

2022-10-11 02:19 UTC, alliequintano requested changes
Hi @ankytastic, thank you for contributing to our tech dictionary! Your definition looks good, i've just made a tiny capitalization fix. 

For the perspective, what we are really looking for is to consider a role on a software team such as QA, developer, designer, etc., and write a perspective from that role. I find the example in the [CONTRIBUTING.md ](https://github.com/cherryontech/website/blob/pit/CONTRIBUTING.md) helpful to clarify this. Also keep in mind how the value will be evaluated in the sentence, which you can see on the site either testing locally or via the Netlify deploy preview. You can find additional instructions in the CONTRIBUTING.md on that as well.

<img width="1731" alt="image" src="https://user-images.githubusercontent.com/3057984/194982135-c5ec5f16-8ec4-42b7-8602-3152e33d320f.png">

2022-10-11 02:19 UTC, alliequintano commented on src/assets/content/dictionary/nginx.md
> +definition: nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server, originally written by Igor Sysoev.
```suggestion
definition: Nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server, originally written by Igor Sysoev.
```

2022-10-26 01:11 UTC, alliequintano commented on src/assets/content/dictionary/SPA.md
> +- meaning: a way for me to make the user experience feel a lot smoother. You can tell when it’s a SPA or multi-page application when navigating between menus often because a multi-page application wi
Did you mean to introduce these fixes with this PR?

2023-04-05 07:01 UTC, closed without merging