Add dictionary definition for "edge case"
cherryontech/website pull request #197
Opened 2022-10-05 21:43 UTC by monicacodes

## This PR fixes...

the lack of dictionary definition and perspective for "edge case"

## What I did...

- Add dictionary definition for edge case
- Add software engineer perspective for edge case

## How to test...

1. Navigate to /dictionary
1. Search "edge case"
1. See if definition and perspective shows up under "edge case"
2. Check grammar and typos

## I learned...

the dictionary definition of what an edge case is in software testing.

2022-10-10 00:53 UTC, alliequintano requested changes
Hi @monicacodes ! Thank you for your contribution. I've added a suggestion to change the wording of your perspective to make it read a bit easier. You can also see that a period is not needed at the end of the meaning because it will be added when the meaning is displayed in the perspective sentence. 

I tested your changes using the Netlify preview. See the screenshot below:
<img width="1721" alt="image" src="https://user-images.githubusercontent.com/3057984/194787383-282204b3-7e77-49c6-b7a9-382fde331f5f.png">

2022-10-10 00:53 UTC, alliequintano commented on src/assets/content/dictionary/edge-case.md
> +- meaning: should not be overlooked or underestimated.
```suggestion
- meaning: a case that, while unusual, should still not be overlooked or underestimated
```

2022-10-10 16:54 UTC, monicacodes commented on src/assets/content/dictionary/edge-case.md
> +- meaning: should not be overlooked or underestimated.
Hi @alliequintano! Thanks for the suggestion. I committed your suggestion. Let me know if anything else needs to be changed.

2022-10-11 00:22 UTC, novellac approved these changes
I'll go ahead and accept this on @alliequintano 's behalf. Thanks and happy Hacktoberfest! 🍁

2022-10-11 00:22 UTC, merged