Add dictionary definition for 'CRM'
cherryontech/website pull request #207
Opened 2022-10-20 11:22 UTC by Amaka202

## This PR fixes...

The lack of definition and perspective for CRM

## What I did...

- Add dictionary definition for CRM
- Add business owner perspective for CRM

## How to test...

1. Navigate to /dictionary
1. Search 'CRM'
1. See if the definition and perspective show up under term 'CRM'
2. Check grammar and typos

## I learned...

 that CRM can also include technology from the dictionary definition

2022-10-20 18:51 UTC, alliequintano requested changes
Hi @Amaka202 ! Thank you for your contribution to our tech dictionary. The definition looks great, i've just left a comment regarding the perspective you've added. Please add me as a reviewer / request re-review once you've made your changes. Thanks!

2022-10-20 18:51 UTC, alliequintano commented on src/assets/content/dictionary/crm.md
> +  role: Business owner
Testing your changes with the Netlify deploy preview, the perspective sentence isn't reading quite right. Also, we can see that the meaning field should not be formatted with a period at the end, since the values fill in parts of a sentence. The [CONTRIBUTING.md](https://github.com/cherryontech/website/blob/pit/CONTRIBUTING.md#tech-dictionary-example) doc provides an example with the necessary formatting.

I've included a screenshot below, and I encourage you to test your changes via either method mentioned in the [CONTRIBUTING.md](https://github.com/cherryontech/website/blob/pit/CONTRIBUTING.md).

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3057984/197031900-2bd351f3-c7e1-4c26-b1a8-4eb84fc4c62c.png">

2022-10-23 14:19 UTC, Amaka202 commented on src/assets/content/dictionary/crm.md
> +  role: Business owner
Thank you so much for the feedbacks @alliequintano I have made updates🙏🏻

2022-10-26 00:41 UTC, alliequintano approved these changes
Great job @Amaka202! Thanks again.

2022-10-26 00:41 UTC, merged