Add definition and perspective for 'KPI'
cherryontech/website pull request #212
Opened 2022-10-20 11:41 UTC by Amaka202

## This PR fixes...

The lack of definition and perspective for 'KPI'

## What I did...

- Add dictionary definition for 'KPI'
- Add Software developer perspective for 'KPI'

## How to test...

1. Navigate to /dictionary
1. Search 'KPI'
1. See if the definition and perspective show up under  the term 'KPI'
2. Check grammar and typos

## I learned...

That KPI is more of a business term other than a software term

2022-10-30 22:24 UTC, alliequintano approved these changes
Hi @Amaka202! I've made a small suggestion to improve the meaning you've provided. I'll be happy to approve with this change. Thank you!

2022-10-30 22:24 UTC, alliequintano commented on src/assets/content/dictionary/kpi.md
> +- meaning: a metric or indicator to measure the work done by software teams in order to remain accountable to set objectives. Eg lines of code, bugs, task completion dealines
```suggestion
- meaning: a way to measure the work I have done in order to remain accountable to set objectives
```

2022-10-30 22:25 UTC, alliequintano requested changes
Hi @Amaka202! I've made a small suggestion to improve the meaning you've provided. I'll be happy to approve with this change. Thank you!

2022-10-31 16:44 UTC, Amaka202 commented
> Hi @Amaka202! I've made a small suggestion to improve the meaning you've provided. I'll be happy to approve with this change. Thank you!

Thank you so much i have made the updates @alliequintano

2022-11-02 22:23 UTC, novellac approved these changes

2022-11-02 22:23 UTC, merged