Add dictonary definition for OSS
cherryontech/website pull request #213
Opened 2022-10-21 19:07 UTC by laurasimsdev

## This PR fixes...

The lack of dictionary definition and perspective for Open Source Software

## What I did...

- Add dictionary definition for OSS
- Add Software Engineer perspective for OSS

## How to test...

_In a list format, tell us how to test this PR._
Ex:

1. Navigate to /dictionary
2. Search "open source software"
3. See if definition and perspective show up under "open source software"
4. Check for grammar and typos

## I learned...

About the preview function in GitHub flavored markdown

2022-10-26 01:27 UTC, alliequintano requested changes
Please see my comments and add me as a reviewer when you're ready for re-review! Thank you.

2022-10-26 01:27 UTC, alliequintano commented on src/assets/content/dictionary/open-source-software-oss.md
> +definition: Open source software is software that is available for anyone to view, copy, change, or distribute for any purpose. Some notable examples of open source software include the Linux operati
```suggestion
definition: Open source software is software that is available for anyone to view, copy, change, or distribute for any purpose. Some notable examples of open source software include the Linux operating system, the Mozilla Firefox browser, Apache HTTP Server software, and LibreOffice productivity software. Every year, open source software contributions are celebrated during October as part of a month-long event called Hacktoberfest.
```

2022-10-26 01:27 UTC, alliequintano commented on src/assets/content/dictionary/open-source-software-oss.md
> +- meaning: is an important part of the software development community, allowing collaboration of large numbers of programmers with diverse perspectives, increasing the speed of innovation
Hi @laurasimsdev ! Thank you so much for your contribution to our tech dictionary. I have just a couple small request to get your changes ready for approval.

Please take a look at our [CONTRIBUTING.md](https://github.com/cherryontech/website/blob/pit/CONTRIBUTING.md) to see the necessary formatting. The `meaning` field will be a part of an existing sentence structure, so we can see the perspective sentence doesn't read quite right when we test your change (via Netlify):
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/3057984/197912829-9f28fe96-733e-41f2-b881-91367fe93ef8.png">

I strongly suggest following the directions listed in the CONTRIBUTING.md for testing locally or via the Netlify deploy preview in order to read your sentence. This helps you catch mistakes like the additional period and capitalization, as well as reading the full sentence for clarity.

2022-10-26 02:21 UTC, laurasimsdev commented
I made the requested updates. Thanks!

2022-10-27 21:43 UTC, alliequintano approved these changes
Great job with the changes 👍 Thanks again for contributing to our tech dictionary!

2022-10-27 21:43 UTC, merged