new definition
cherryontech/website pull request #223
Opened 2023-09-22 15:27 UTC by katiyelae

## This PR fixes...

_Remove the example below. Then, add the related issue after the hash. Lastly, tell us what problems this PR is meant to solve._
Ex: This PR fixes #999. We didn't have a unicorn, so we went to the unicorn store and got one.

## What I did...

_Remove the example below. Then, list out the work you have done, in bullet form._
Ex:

- one
- two

## How to test...

_In a list format, tell us how to test this PR._
Ex:

1. Navigate to https://example.com/cats
1. Click on magic button
1. See coolest cat

## I learned...

_Did you run into any interesting issues while making this PR? If you learned anything you would like to share, we'd love to know! Even if it is a fun fact or GIF!_

2023-09-22 15:32 UTC, katiyelae commented
This is a new definition for the COT website.

2023-09-22 15:34 UTC, alliequintano commented
@katiyelae great! Hit the 'edit' button to fill out the PR template with the necessary information:
<img width="1098" alt="image" src="https://github.com/cherryontech/website/assets/3057984/a2a7567e-9ad3-4701-8c04-cb8afcb07cab">

2023-10-10 15:45 UTC, alliequintano requested changes
Hey @katiyelae! I checked out the deploy preview, and it looks like the definition should be plain text:
<img width="1784" alt="image" src="https://github.com/cherryontech/website/assets/3057984/8a55faca-4928-487c-a615-c36660bc9835">

When you push your fix for this, be sure to test your changes locally and check the deploy preview on your PR!

2023-10-13 18:22 UTC, alliequintano approved these changes

2023-10-13 18:22 UTC, merged