Update README.md
cherryontech/website pull request #255
Opened 2024-10-27 14:59 UTC by ashvin2005

I have made a refined and visually engaging version of your README for Cherry On Tech’s website, with enhanced structure, clarity, and more emojis

## This PR fixes...

_Remove the example below. Then, add the related issue after the hash. Lastly, tell us what problems this PR is meant to solve._
Ex: This PR fixes #999. We didn't have a unicorn, so we went to the unicorn store and got one.

## What I did...

_Remove the example below. Then, list out the work you have done, in bullet form._
Ex:

- one
- two

## How to test...

_In a list format, tell us how to test this PR._
Ex:

1. Navigate to https://example.com/cats
1. Click on magic button
1. See coolest cat

## I learned...

_Did you run into any interesting issues while making this PR? If you learned anything you would like to share, we'd love to know! Even if it is a fun fact or GIF!_

2024-10-27 15:28 UTC, novellac requested changes
This PR doesn't fix any issues, and it introduces a couple of new ones. If you'd like to contribute, we'd prefer you do things like fix, update, or create dictionary entries, [as outlined in `CONTRIBUTING.md`](https://github.com/cherryontech/website/blob/pit/CONTRIBUTING.md).
However, I understand it's the end of Hacktoberfest, so I've left the PR open. You're welcome to make the requested changes and request another review. Best of luck with the rest of Hacktoberfest!

2024-10-27 15:28 UTC, novellac commented on README.md
> -We welcome you to contribute to our "Tech Dictionary," where we share tech terms from different _perspectives_. To get involved, read [CONTRIBUTING.md](CONTRIBUTING.md).
Issue: This is a very important section and should not be removed.

2024-10-27 15:28 UTC, novellac commented on README.md
> -1. Run `gridsome develop` to start a local dev server. In the terminal, you will see an address such as `http://localhost:8080/`. Navigate to that address in a browser to see the project in action.
Issue: The installation steps are important to remain here. If you'd like to enhance this section by moving the node check instructions (as you added on ln15), feel free to do that.

2025-09-17 17:24 UTC, alliequintano commented
Closing because this PR is old.

2025-09-17 17:24 UTC, closed without merging